HRproject/HRproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView,ListView
from app import views
from app.models import Adminmodel
from manager import urls as m_url
from applicant import urls as ap_url
from interviewer import urls as in_url
from hrhead import urls as hr_url
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',TemplateView.as_view(template_name='index.html'),name='index'),
    path('admin_login_page/',TemplateView.as_view(template_name='admin/admin_login_page.html'),name="admin_login_page"),
    path('admin_success/',views.admin_success.as_view(),name='admin_success'),
    path('add_employee/',views.add_employee.as_view(),name='add_employee'),
    path('view_all/',views.view_all.as_view(),name='view_all'),
    path('modify_employee/',views.modify_employee.as_view(),name='modify_employee'),
    path('update_employee/<int:pk>',views.update_employee.as_view(),name='update_employee'),
    path('delete_employee/', ListView.as_view(template_name='admin/delete_employee.html', model=Adminmodel), name='delete_employee'),
    path('delete_emplo/<int:pk>',views.delete_emplo.as_view(),name='delete_emplo'),
    path('',include(m_url)),
    path('',include(ap_url)),
    path('',include(in_url)),
    path('',include(hr_url))


]

HRproject/hrhead/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

from hrhead import views

urlpatterns = [
    path('hrhead_login_page/',views.hrhead_login_page.as_view(),name='hrhead_login_page'),
    path('hrhead_home_page/',views.hrhead_home_page.as_view(),name='hrhead_home_page'),
    path('view_selected_applicant/',views.view_selected_applicant.as_view(),name='view_selected_applicant'),
    path('view_rejected_applicant/',views.view_rejected_applicant.as_view(),name='view_rejected_applicant')
]

HRproject/interviewer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import TemplateView

from interviewer import views

urlpatterns = [
    path('interviewer_login_page/',views.interviewer_login_page.as_view(),name='interviewer_login_page'),
    path('interviewer_home_page/',views.interviewer_home_page.as_view(),name='interviewer_home_page'),
    path('interviewer_main_page/',views.interviewer_main_page.as_view(),name='interviewer_main_page')


]

HRproject/interviewer/models.py
from django.db import models
from applicant.models import ApplicantApllicationModel
from app.models import Adminmodel

class Interviewmodel(models.Model):
    intr_id=models.IntegerField(unique=True)
    interviewer=models.ForeignKey(Adminmodel,on_delete=models.CASCADE)
    sch_date=models.CharField(max_length=20)
    app_id=models.ForeignKey(ApplicantApllicationModel,on_delete=models.CASCADE)
    result=models.CharField(max_length=20)



    def __str__(self):
        return str(self.app_id)

HRproject/interviewer/forms.py
from django import forms
from  .models import Interviewmodel

class Interviewform(forms.ModelForm):
    class Meta:
        model=Interviewmodel
        fields="__all__"

HRproject/interviewer/views.py
from django.shortcuts import render,redirect
from django.views.generic import View
from django.contrib import messages
from .models import Interviewmodel
from applicant.models import ApplicantApllicationModel
from app.models import Adminmodel
from .forms import Interviewform


class interviewer_login_page(View):
    def get(self,request):
        return render(request,"interviewer/interviewer_login_page.html")
    def post(self,request):
        un=request.POST.get('bt7')
        pd=request.POST.get('bt8')
        try:
            e=Adminmodel.objects.get(Email=un,Password=pd,Designation='INTERVIWER')
            ap=ApplicantApllicationModel.objects.values('id')
            return render(request,"interviewer/interviewer_home_page.html",{"data":ap})
        except Adminmodel.DoesNotExist:
            messages.success(request,"INAVALID USERNAME OR PASSWORD!")
            return redirect('interviewer_login_page')

class interviewer_home_page(View):
    def get(self,request):
        print('1')
        ap=ApplicantApllicationModel.objects.values('id')
        print('2')
        print(ap)
        return render(request,"interviewer/interviewer_home_page.html",{"data":ap})
    def post(self,request):
        sf=request.POST.get('w1')
        f=Interviewform
        return render(request,"interviewer/interviewer_main_page.html",{"form":f,"dt":sf})

class interviewer_main_page(View):
    def post(self,request):
        ifm=Interviewform(request.POST)
        if ifm.is_valid():
            ifm.save()
            messages.success(request,"interview date successfully added")
            return render(request,'interviewer/interviewer_main_page.html',{"form":ifm})
        else:
            return render(request,"interviewer/interviewer_home_page.html",{"form":ifm})
    def get(self,request):
        return render(request,"interviewer/interviewer_main_page.html")

def interview_login_page(request):
    ai=ApplicantApllicationModel.objects.get('id')
    return render(request,"interviewer/interviewer_login_page.html",{"data":ai})

HRproject/templates/interviewer/interviewer_home_page.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'int css/int.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
        <br>
  <table align="center"><tr>
      <th><img src="{% static 'images/hr logo.png' %}" width="100" height="100"> </th><br>
      <th>
  <h1 align="center" style="font-family: Algerian;color:deeppink">HR OPERATION MANAGEMENT</h1>
          </th>
  </tr></table>
  <marquee><h3 style="font-family: Algerian;color: lime"> YOUR LIFE IN YOUR HANDS!!!!!!!!!!!!!!!!!</h3></marquee>
        <BR>
        <BR>
        <BR>
<h2 align="center" style="font-family: 'Arial Black';text-shadow: 5px 5px 5px blue">CONDUCTING AND PREPARING FINAL SELECTION LIST</h2>
<br>
        <br>
        <form action="{% url 'interviewer_home_page' %}" method="post">
            {% csrf_token %}

        <table align="center" border="0">
            <tr>
                <th style="font-family: Algerian">SELECT AN APPLICANT-ID</th>
                <th><select name="w1" class="form-control">
                    {% for x in data %}
                        <option value="{{ x.id }}">{{ x.id }}</option>
                    {% endfor %}
                </select> </th>
            </tr>
        <tr>
            <th style="text-align: center"><br>
                <br><button type="submit">GET DETAILS</button> </th>
        </tr>
        </table>
        </form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

HRproject/templates/interviewer/interviewer_login_page.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'int css/int.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
    <br>
  <table align="center"><tr>
      <th><img src="{% static 'images/hr logo.png' %}" width="100" height="100"> </th><br>
      <th>
  <h1 align="center" style="font-family: Algerian;color:deeppink">HR OPERATION MANAGEMENT</h1>
          </th>
  </tr></table>
  <marquee><h3 style="font-family: Algerian;color: lime"> YOUR LIFE IN YOUR HANDS!!!!!!!!!!!!!!!!!</h3></marquee>
{% include 'index_menu.html' %}

<br>
  <form method="post">
      {% csrf_token %}
      <h1 align="center" style="font-family: Arial;color: green;text-shadow: 5px 5px 5px blanchedalmond">INTERVIEWER LOGIN PAGE</h1>
  <table align="center" border="0">
      <tr>
          <th> EMAIL</th>
          <th><input type="text" placeholder="@gmail.com" required name="bt7"></th>
      </tr>
      <tr>
          <th>PASSWORD</th>
          <th><input type="password" placeholder="*********" required name="bt8"></th>
      </tr>
      <tr>
          <br>
          <th colspan="3" style="text-align: center">
              <br><button type="submit" class="btn btn-success">LOGIN</button></th>
      </tr>
      {% for x in messages %}
          <tr>
          <th align="center" style="font-family: Algerian">{{ x }}</th>
          </tr>
      {% endfor %}
  </table>
  </form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

HRproject/templates/interviewer/interviewer_main_page.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'int css/int.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
           <br>
  <table align="center"><tr>
      <th><img src="{% static 'images/hr logo.png' %}" width="100" height="100"> </th><br>
      <th>
  <h1 align="center" style="font-family: Algerian;color:deeppink">HR OPERATION MANAGEMENT</h1>
          </th>
  </tr></table>
  <marquee><h3 style="font-family: Algerian;color: lime"> YOUR LIFE IN YOUR HANDS!!!!!!!!!!!!!!!!!</h3></marquee>
        <BR>
           <br>
           <a href="{% url 'interviewer_login_page' %}"><button type="submit" class="btn btn-primary btn-lg" style="width: 300px"> LOGOUT</button></a>
           <br>
           <h2 align="center" style="font-family: Algerian;text-shadow: 5px 5px 5px green">ASSIGN AN INTERVIEW FOR AN APPLICANT</h2>
           <br>


           <form action="{% url 'interviewer_main_page' %}" method="post">
               {% csrf_token %}
  <table align="center">
      <tr><th style="font-family: Algerian;color: red">{{ form.intr_id.label }}</th><th>{{ form.intr_id }}</th></tr>
      <tr><th style="font-family: Algerian;color: red">{{ form.interviewer.label }}</th><th>{{ form.interviewer }}</th></tr>
      <tr><th style="font-family: Algerian;color: red">SCHEDULE_TIME STAMP</th><th><input type="date" required name="sch_date" id="id_sch_date"></th></tr>
      <tr><th style="font-family: Algerian;color: red">APPLICANT ID</th><th><select name="app_id" id="id_app_id">
          <option value="" selected>----------</option>
          <option value="{{ dt }}">{{ dt }}</option>
      </select> </th></tr>
      <tr><th style="font-family: Algerian;color: red">{{ form.result.label }}</th><th>{{ form.result }}</th></tr>
      <tr>
          <th style="text-align: center" colspan="3"><br><button type="submit">ADD TO INTERVIEW </button> </th>
      </tr>
      {% for x in messages %}
          <tr>
          <th style="font-family: Algerian;text-align: center;color: red">{{ x }}</th>
          </tr>
      {% endfor %}
  </table>
           </form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>